### ISSUE TITLE
Example Gallery. SinAndCosFunctionPlot. Need to add "self.wait()"

### ISSUE THREAD

**Issue by ManuelMendozaUPM** [ManimCommunity/manim-website#7]
If not included "self.wait()" in the construct method no video is generated, as no animarion is lauched, and an error is arisen.

**Comment by behackl** [comment]
Thank you for the report! We are working on making manim detect automatically whether there are any animations in the scene, and then either render a video or just an image accordingly. In the meantime, you can always render scenes without animations by passing the `-s` flag to generate an image.

I'm closing this issue here, as this repository is strictly about the page https://www.manim.community -- issues for documentation etc. should also go to our main repository, http://github.com/manimCommunity/manim. There, https://github.com/ManimCommunity/manim/issues/1052 already covers the issue you are describing here.
